//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMarxheim.Modelle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medizin
    {
        public int Medizinid { get; set; }
        public int Personid { get; set; }
        public int Adressid { get; set; }
        public string Name { get; set; }
        public Nullable<int> pieces { get; set; }
        public Nullable<System.DateTime> date_movement { get; set; }
        public string barcode { get; set; }
    
        public virtual Persons Person { get; set; }
        public virtual Standord Standord { get; set; }
    }
}
