//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMarxheim.Modelle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Standord()
        {
            this.Medizins = new HashSet<Medizin>();
        }
    
        public int Adressid { get; set; }
        public string Strasse { get; set; }
        public Nullable<int> plz { get; set; }
        public string ort { get; set; }
        public string Land { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medizin> Medizins { get; set; }
    }
}
